kind: DataMapper
version: v1
metadata:
  name: "Kaggle Global News Dataset"
  description: "Mapping for Kaggle Global News Dataset fields"
dataset: kaggle
dateFormat: "2006-01-02 15:04:05.000000"
fieldMappings:
 - source: "title"
   sourceType: "string"
   target: "Title"
   targetType: "string"
   required: true
 - source: "author"
   sourceType: "string"
   target: "Author"
   targetType: "string"
   required: true
 - source: "description"
   sourceType: "string"
   target: "Description"
   targetType: "string"
   required: true
 - source: "content"
   sourceType: "string"
   target: "Content"
   targetType: "string"
   required: true
 - source: "url"
   sourceType: "url"
   target: "URL"
   targetType: "url"
   required: false
 - source: "published_at"
   sourceType: "datetime"
   target: "Metadata.PublishedAt"
   targetType: "datetime"
   required: false
 - source: "source_id"
   sourceType: "string"
   target: "Metadata.SourceId"
   targetType: "string"
   required: false
 - source: "source_name"
   sourceType: "string"
   target: "Metadata.SourceName"
   targetType: "string"
   required: false
 - source: "description"
   sourceType: "string"
   target: "Description"
   targetType: "string"
   required: false
 - source: "category"
   sourceType: "string"
   target: "Metadata.Category"
   targetType: "string"
   required: false
