// Package openapi_spec Code generated by swaggo/swag. DO NOT EDIT
package openapi_spec

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@newshunter.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://opensource.org/licenses/Apache-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/articles/search": {
            "get": {
                "description": "Simple text search with automatic field selection and weighting. Cacheable and bookmarkable. Application determines optimal search strategy based on index configuration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Simple query string search",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"climate change\"",
                        "description": "SearchStringQuery query text",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "description": "Results per page (default: 100, max: 10000)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor (base64-encoded from previous response)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"english\"",
                        "description": "SearchStringQuery language: english, serbian (default: english)",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SearchStringQuery results with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/dto.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing or invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/articles/semantic_search": {
            "get": {
                "description": "Perform vector-based semantic search using the embedding model. Supports pagination via cursor. Application determines optimal search strategy based on index configuration. Results are cacheable and bookmarkable.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Vector-based semantic search",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"climate change\"",
                        "description": "SearchStringQuery query text",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "example": 10,
                        "description": "Results per page (default: 100, max: 10000)",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor (base64-encoded from previous response)",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SearchStringQuery results with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/dto.SemanticSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing or invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/articles/structured": {
            "post": {
                "description": "Execute structured search queries with explicit control over fields, weights, and operators. Supports match and multi_match query types. Follows Elasticsearch query DSL pattern.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Structured search API",
                "parameters": [
                    {
                        "description": "Structured search request with query wrapper",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SearchStringQuery results with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/dto.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid query structure or parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "501": {
                        "description": "Query type not supported by searcher backend",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Article": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/dto.ArticleMetadata"
                },
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "format": "string"
                }
            }
        },
        "dto.ArticleMetadata": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Content metadata",
                    "type": "string"
                },
                "importedAt": {
                    "description": "System metadata",
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "sourceId": {
                    "description": "Essential source tracking",
                    "type": "string"
                },
                "sourceName": {
                    "type": "string"
                }
            }
        },
        "dto.ArticleSearchResult": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "Embedded Article struct for search results",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Article"
                        }
                    ]
                },
                "score": {
                    "description": "Score rank between 0 and 1",
                    "type": "number"
                },
                "score_normalized": {
                    "description": "ScoreNormalized is the normalized(between 0-1) score",
                    "type": "number"
                }
            }
        },
        "dto.BooleanParams": {
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                }
            }
        },
        "dto.MatchParams": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "fuzziness": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "dto.MultiMatchParams": {
            "type": "object",
            "properties": {
                "field_weights": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "dto.PhraseParams": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "string"
                },
                "query": {
                    "type": "string"
                },
                "slop": {
                    "type": "integer"
                }
            }
        },
        "dto.QueryWrapper": {
            "type": "object",
            "properties": {
                "boolean": {
                    "$ref": "#/definitions/dto.BooleanParams"
                },
                "match": {
                    "$ref": "#/definitions/dto.MatchParams"
                },
                "multi_match": {
                    "$ref": "#/definitions/dto.MultiMatchParams"
                },
                "phrase": {
                    "$ref": "#/definitions/dto.PhraseParams"
                }
            }
        },
        "dto.SearchRequest": {
            "type": "object",
            "properties": {
                "cursor": {
                    "type": "string"
                },
                "query": {
                    "$ref": "#/definitions/dto.QueryWrapper"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "dto.SearchResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "hits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ArticleSearchResult"
                    }
                },
                "max_score": {
                    "type": "number"
                },
                "next_cursor": {
                    "type": "string"
                },
                "page_max_score": {
                    "type": "number"
                },
                "total_matches": {
                    "type": "integer"
                }
            }
        },
        "dto.SemanticSearchResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "hits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Article"
                    }
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "News Hunter API",
	Description:      "A full-text search engine for exploring multilingual news headlines and articles",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
