// Package openapi_spec Code generated by swaggo/swag. DO NOT EDIT
package openapi_spec

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@newshunter.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://opensource.org/licenses/Apache-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/articles/search": {
            "get": {
                "description": "Search for news articles using full-text query with cursor-based pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Full-text news search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination (base64-encoded)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default: 100, max: 10000)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/router.FTSSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Article": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/dto.ArticleMetadata"
                },
                "subtitle": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string",
                    "format": "string"
                }
            }
        },
        "dto.ArticleMetadata": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Content metadata",
                    "type": "string"
                },
                "importedAt": {
                    "description": "System metadata",
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "sourceId": {
                    "description": "Essential source tracking",
                    "type": "string"
                },
                "sourceName": {
                    "type": "string"
                }
            }
        },
        "dto.ArticleSearchResult": {
            "type": "object",
            "properties": {
                "article": {
                    "description": "Embedded Article struct for search results",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Article"
                        }
                    ]
                },
                "rank": {
                    "description": "Score based on search relevance",
                    "type": "number"
                }
            }
        },
        "router.FTSSearchResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ArticleSearchResult"
                    }
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "News Hunter API",
	Description:      "A full-text search engine for exploring multilingual news headlines and articles",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
